@startuml
'https://plantuml.com/class-diagram

class Main{
+ static void main(String[] args)
}

class Stream{
- String name
'utilities
- ArrayList<User> users
- ArrayList<Film> films
- ArrayList<Series> series
- String userDataPath
- TextUI ui
- FileIO io
- ArrayList<String> listOfActions;
- String seriesDataPath
- String filmDataPath
'constructor
+ Stream(String name)
'methods
- void setup()
' setup er til er at læse data
+ runStartMenu()
+ void createUser()
' skal createUser være void? Det er den i matador
' createUser skal vel checke om der er andre med det brugernavn
+ loginUser()
' skal loginUser være void?
' den skal vel checke om der er en user med det username og tjekke om loginnet er korrekt
+ runDialog()
' i runDialog kan man vælge at søge
- void quitProgram()
}


class User{
- String name
- ArrayList<Series> seenSeries
- ArrayList<Film> seenFilm
- ArrayList<Video> savedVideo
+ boolean watchVideo()
+ boolean addToSaved()
}

class FileIO{
+ String[] readFilmData(String path)
+ String[] readSeriesData(String path)
+ void saveData(ArrayList<User> users, String path)
+ String[] readFilmData(String path, int length)
+ String[] readSeriesData(String path, int length)
+ ArrayList<User> readSaveData(String path, int length)
}

class TextUI{
- Scanner scanner
+ void displayList()
+ void displayMsg(String s)
+ int promptNumeric(String msg)
+ String promptText(String msg)
+ int promptChoice(String msg, ArrayList<String> list)
}

interface IVideo {
boolean watchVideo()
String getReleaseDate()
String getName()
String getGenre()
float getRating()
String playVideo()
}

abstract Class Video{
- String name
- String genre
- float rating
- boolean hasSeen
- String releaseDate
'constructor
+ Video()
}

class Series{
- ArrayList<String [3]> seenEpisodes
- int seasons
- int episodes
+ Series (ArrayList<String> seriesData)
+ getSeason()
+ getEpisode()
+ createSeries(ArrayList<String> seriesData)
}

class Film {
'constructor
+ Film (ArrayList<String> filmData)
- ArrayList<String> MovieName()
+ createFilms(ArrayList<String> filmData))
}


class Search{
+ ArrayList<Video> search()
'methods til de forskellige søgemuligheder
' Skal disse returnere objekterne fra video?
+ searchGenre()
+ searchName()
+ searchRating()
+ searchReleasedate()
'skal vi have funktioner der kun søger blandt serier og film adskilt?
}

IVideo *.. Video

Video <|-- Series
Video <|-- Film

Main *-- Stream

Stream *-- User
Stream *-- FileIO
Stream *-- TextUI
Stream *-- IVideo
Stream *-- Search

@enduml