@startuml

rectangle "toString'n'Chill" {

object User
object Login
object SignUp
object Film
object Series
object StartMenu
object Stream
object History
object Saved
object Genre
object Seasons
object Rating
object ReleaseDate
object Search
object Video

User *-- Stream
Login *-- User
User *-- SignUp


StartMenu *-- Login
StartMenu *-- SignUp



Stream o-- History
Stream o-- Saved
Stream *-- Video
Stream *-- Search

Video <|-- Series
Video <|-- Film

Series *-- Genre
Series *-- Seasons
Series *-- Rating
Series *-- ReleaseDate

Film *-- Genre
Film *-- Rating
Film *-- ReleaseDate


}


@enduml